# Generated by Django 2.2.4 on 2019-10-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=150, verbose_name='LastName')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('password', models.CharField(max_length=50, verbose_name='First Name')),
                ('photo', models.ImageField(max_length=200, upload_to='images/', verbose_name='Image')),
                ('credit_card_number', models.CharField(max_length=20, verbose_name='Phone')),
                ('status', models.BooleanField(default=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('abbreviation', models.TextField(verbose_name='Abbreviation')),
                ('status', models.BooleanField(default=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(max_length=200, upload_to='images/', verbose_name='Image')),
                ('quantity', models.IntegerField(max_length=10, verbose_name='Quantity')),
                ('status', models.BooleanField(default=True, verbose_name='State')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Category')),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Country')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_date', models.DateField(auto_now_add=True, verbose_name='Shopping date')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Client')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Product')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Country'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Gender'),
        ),
    ]
